CREATE DATABASE IF NOT EXISTS trial;
USE trial;

CREATE TABLE IF NOT EXISTS trial_table (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    amount DOUBLE NOT NULL DEFAULT 0,
    category VARCHAR(64),
    checklist1 BOOLEAN DEFAULT FALSE,
    checklist2 BOOLEAN DEFAULT FALSE,
    color VARCHAR(16),
    address TEXT
);
